const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
const LOAD_INFO_VALUE = 'LOAD_INFO_VALUE';
const SET_CATEGORIES_DATA = 'SET_CATEGORIES_DATA';
const SET_SCOPES_DATA = 'SET_SCOPES_DATA';
const TOGGLE_ACTIVE_CATEGORY = 'TOGGLE_ACTIVE_CATEGORY';
const SET_ALL_DATA = 'SET_ALL_DATA';
const DELETE_ITEM = 'DELETE_ITEM';
const USERS_FETCH_ALL_SUCCESS = 'USERS_FETCH_ALL_SUCCESS';
const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED';
const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED';
const GET_ALL_DATA = 'GET_ALL_DATA';
const GET_ALL_DATA_SUCCESS = 'GET_ALL_DATA_SUCCESS';
const TOGGLE_MODAL_VISIBLE = 'TOGGLE_MODAL_VISIBLE';

export {
    CLICK_UPDATE_VALUE,
    LOAD_INFO_VALUE,
    SET_CATEGORIES_DATA,
    SET_SCOPES_DATA,
    TOGGLE_ACTIVE_CATEGORY,
    SET_ALL_DATA,
    DELETE_ITEM,
    USERS_FETCH_REQUESTED,
    USERS_FETCH_ALL_SUCCESS,
    USERS_FETCH_FAILED,
    GET_ALL_DATA,
    GET_ALL_DATA_SUCCESS,
    TOGGLE_MODAL_VISIBLE
}